дз по первому модулю
js-tasks-ru/jsbasic-20210906-2_arina-mamatkazina pull request #2
Opened 2021-09-12 11:48 UTC by mamatkazina

2021-09-12 11:50 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-09-12 15:40 UTC, SinimaWath requested changes

2021-09-12 15:40 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  return false;
Когда результат операции boolean - можно писать без if:

`return !!name && ....`

2021-09-12 15:40 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  return false;
- Давай тут без if, он излишен. Можно сразу вернуть результат операции str.indexOf('1XBET') !== -1 || str.indexOf('XXX') !== -1
- indexOf - давай заменим на более подходящий includes

2021-09-12 15:40 UTC, SinimaWath commented on 1-module/5-task/index.js
> +    str = str.slice(0, maxlength-1);
перезаписывать аргумент, зачастую очень неявное поведение, которое приводит к ошибкам.

Давай создавать новую переменную

2021-09-14 18:17 UTC, mamatkazina commented
Добрый вечер, а мне нужно отправить еще раз? Просто в гите у меня все
приняли, а на платформе дз не зачтено.

вс, 12 сент. 2021 г. в 18:40, Vladik Tarasov ***@***.***>:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In 1-module/2-task/index.js
> <https://github.com/js-tasks-ru/jsbasic-20210906-2_arina-mamatkazina/pull/2#discussion_r706855436>
> :
>
> > +  if(name && (name.length >= 4) && (name.indexOf(' ') === -1)){
>
> +    return true;
>
> +  }
>
> +  return false;
>
>
> Когда результат операции boolean - можно писать без if:
>
> return !!name && ....
> ------------------------------
>
> In 1-module/4-task/index.js
> <https://github.com/js-tasks-ru/jsbasic-20210906-2_arina-mamatkazina/pull/2#discussion_r706855497>
> :
>
> > +  if(str.indexOf('1XBET') !== -1 || str.indexOf('XXX') !== -1)
>
> +  {
>
> +    return true;
>
> +  }
>
> +  return false;
>
>
>
>    - Давай тут без if, он излишен. Можно сразу вернуть результат операции
>    str.indexOf('1XBET') !== -1 || str.indexOf('XXX') !== -1
>    - indexOf - давай заменим на более подходящий includes
>
> ------------------------------
>
> In 1-module/5-task/index.js
> <https://github.com/js-tasks-ru/jsbasic-20210906-2_arina-mamatkazina/pull/2#discussion_r706855547>
> :
>
> > @@ -1,3 +1,9 @@
>
>  function truncate(str, maxlength) {
>
> -  // ваш код...
>
> +
>
> +  if(str.length > maxlength){
>
> +    str = str.slice(0, maxlength-1);
>
>
> перезаписывать аргумент, зачастую очень неявное поведение, которое
> приводит к ошибкам.
>
> Давай создавать новую переменную
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/js-tasks-ru/jsbasic-20210906-2_arina-mamatkazina/pull/2#pullrequestreview-752172033>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUNXGADUNSWDZRMQI4PCN4LUBTCYNANCNFSM5D4AM2ZA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-09-14 19:57 UTC, SinimaWath commented
Нужно исправить замечания, которые оставил, и тогда приму ;)

2021-09-16 17:27 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-09-18 18:15 UTC, mamatkazina commented
Добрый вечер, я вроде все исправила еще несколько дней назад, а изменений
на платформе так и не произошло.

чт, 16 сент. 2021 г. в 20:27, javascript-ru ***@***.***>:

> Добавляю преподавателя ***@***.*** <https://github.com/SinimaWath>) для
> код-ревью.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/js-tasks-ru/jsbasic-20210906-2_arina-mamatkazina/pull/2#issuecomment-921092387>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUNXGAGUWWBG256D5CYNENTUCISI7ANCNFSM5D4AM2ZA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-09-19 12:02 UTC, SinimaWath approved these changes

2021-09-19 12:02 UTC, merged